modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="kobolds"
version="3.2.8"
displayName="Kobolds"
displayURL="https://discord.gg/s7QaYGUzZU"
logoFile="logo.png"
credits="Jusey1, Giodude1580, Burack, Lorian Ross"
authors="Jusey1"
description="Tiny Lizards"


[[dependencies.kobolds]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.6]"
    ordering="NONE"
    side="BOTH"
